name: Run GRTresna Tests (GCC)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mpi: ['TRUE', 'FALSE']
      fail-fast: false
    name: GCC MPI = ${{ matrix.mpi }}
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1
      GRCHOMBO_HOME: ${{ github.workspace }}/GRChombo
      BUILD_ARGS: MPI=${{ matrix.mpi}}
  
    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/GRChombo
        path: GRChombo

    - name: Checkout GRTresna
      uses: actions/checkout@v2
      with:
        path: GRTresna

    - name: Install Chombo dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev libgetopt-complete-perl

    - name: Set Compilers
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
        sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100
    
    - name: Build Chombo
      run: |
        if [[ "${{ matrix.mpi }}" == "TRUE" ]]; then
          MAKE_DEFS_FILE=$GRCHOMBO_HOME/InstallNotes/MakeDefsLocalExamples/ubuntu-gcc.Make.defs.local
        else
          MAKE_DEFS_FILE=$GRCHOMBO_HOME/InstallNotes/MakeDefsLocalExamples/ubuntu-gcc-nompi.Make.defs.local
        fi
        cp $MAKE_DEFS_FILE $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools $BUILD_ARGS
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRTresna Tests
      run: make all -j 4 $BUILD_ARGS
      working-directory: ${{ github.workspace }}/GRTresna/Tests/PeriodicScalarFieldTest

    - name: Run GRTresna Tests
      run: |
        if [[ "${{ matrix.mpi }}" == "TRUE" ]]; then
          make run -j 2 $BUILD_ARGS RUN='mpirun -np 2 --oversubscribe ./'
        else
          make run -j 2 $BUILD_ARGS
        fi
      working-directory: ${{ github.workspace }}/GRTresna/Tests/PeriodicScalarFieldTest
