name: Run GRTresna Tests (Intel classic)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mpi: ['TRUE', 'FALSE']
      fail-fast: false
    name: Intel (classic) MPI = ${{ matrix.mpi }}
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1
      GRCHOMBO_HOME: ${{ github.workspace }}/GRChombo
      BUILD_ARGS: MPI=${{ matrix.mpi}}
  
    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v2
      with:
        repository: GRChombo/GRChombo
        path: GRChombo

    - name: Checkout GRTresna
      uses: actions/checkout@v2
      with:
        path: GRTresna

    - name: Install Chombo dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh libgetopt-complete-perl
        
    - name: Install Intel compilers
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.4 intel-oneapi-compiler-fortran-2023.2.4 intel-oneapi-mkl-2023.2.0 intel-oneapi-openmp-2023.2.4
      working-directory: /tmp

    - name: Install Intel MPI
      if: matrix.mpi == 'TRUE'
      run: |
        sudo apt-get -y install intel-oneapi-mpi intel-oneapi-mpi-devel 
    
    - name: Build Chombo
      run: |
        source /opt/intel/oneapi/setvars.sh
        MAKE_DEFS_FILE=$GRCHOMBO_HOME/InstallNotes/MakeDefsLocalExamples/intel-classic-no-hdf5-minimal.Make.defs.local
        cp $MAKE_DEFS_FILE $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools $BUILD_ARGS
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRTresna Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make all -j 4 $BUILD_ARGS
      working-directory: ${{ github.workspace }}/GRTresna/Tests/PeriodicScalarFieldTest

    - name: Run GRTresna Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make run -j 2 $BUILD_ARGS
      working-directory: ${{ github.workspace }}/GRTresna/Tests/PeriodicScalarFieldTest
